# Generated by Django 3.2.5 on 2022-11-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['year__year', 'month__month', 'day__day'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'disambiguator'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='classinfo.course')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='classinfo.date')),
            ],
            options={
                'ordering': ['course', 'style_name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='classinfo.learner')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='classinfo.style')),
            ],
            options={
                'ordering': ['style', 'learner'],
            },
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'disambiguator'), name='unique_student'),
        ),
        migrations.AddField(
            model_name='date',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='classinfo.day'),
        ),
        migrations.AddField(
            model_name='date',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='classinfo.month'),
        ),
        migrations.AddField(
            model_name='date',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='classinfo.year'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_name',), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('course', 'style_name', 'date'), name='unique_section'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('style', 'learner'), name='unique_registration'),
        ),
        migrations.AddConstraint(
            model_name='date',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'day'), name='unique_date'),
        ),
    ]
