# Generated by Django 3.2.5 on 2022-11-09 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['style', 'course_name']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['course', 'date', 'learner']},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['style_name']},
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course',
        ),
        migrations.RemoveConstraint(
            model_name='learner',
            name='unique_student',
        ),
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_registration',
        ),
        migrations.RemoveConstraint(
            model_name='style',
            name='unique_section',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='style',
        ),
        migrations.RemoveField(
            model_name='style',
            name='course',
        ),
        migrations.RemoveField(
            model_name='style',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='course_intro',
            field=models.TextField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='classinfo.style'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='classinfo.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='classinfo.date'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('style', 'course_name'), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'disambiguator'), name='unique_learner'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('course', 'date', 'learner'), name='unique_registration'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('style_name',), name='unique_style'),
        ),
    ]
